settings:
  commit_msg: "Update README with actions"
  max_lines: 5
  readme_file: "./README.md"
  disabled_events:
    - "push"
    - "issues"
    - "review"
    - "star"
    - "wiki"
    - "fork"
  commit_name: "Github-Actions"
messages:
  comments: "ğŸ’¬ Commented in {REPO}"
  issue_opened: "â—ï¸ Opened issue in {REPO}"
  issue_closed: "âœ”ï¸ Closed issue in {REPO}"
  pr_opened: "ğŸ’ª Opened PR in {REPO}"
  pr_closed: "âŒ Closed PR in {REPO}"
  pr_merged: "ğŸ‰ Merged PR in {REPO}"
  create_repo: "ğŸ“” Created new repository {REPO}"
  fork_repo: "ğŸ”± Forked {FORK} from {REPO}"
  wiki_create: "ğŸ“– Created new wiki page {WIKI} in {REPO}"
  added_member: "ğŸ¤ Became collaborator on {REPO}"
  changes_approved: "ğŸ‘ Approved {REPO}"
  changes_requested: "ğŸ”´ Requested changes in {REPO}"
  new_release: "âœŒï¸ Released {ID} in {REPO}"
  new_star: "â­ Starred {REPO}"
